image: node:14.9.0
stages:
  - build
variables:
  GIT_SUBMODULE_STRATEGY: recursive
before_script:
  - echo ======= before script start ========
  - export _TOKEN=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
  - export GENERATE_SOURCEMAP=false
  - node -v
  - npm -v
  - unset CI
  - echo ======= before script done ========
cache:
  paths:
  - node_modules/
build_project:
  stage: build
  script:
    - echo ======= build started ========
    - npm install
    - npm run-script test
    - npm run-script dist
    - cd dist
    - npm pack
    - echo ======= build finished ========
  artifacts:
      paths:
        - dist/*.tgz
      expire_in: 24 hrs
  only:
    - master
    - merge_requests
build_release:
  stage: build
  script:
    - echo ======= release started ========
    - npm install
    - npm run-script test
    - npm run-script dist
    - cd dist
    - npm publish
    - echo ======= release finished ========
  artifacts:
      paths:
        - dist/*.tgz
      expire_in: 48 hrs
  only:
    - /^release/.*$/