image: node:14.19.1
stages:
  - build
variables:
  GIT_SUBMODULE_STRATEGY: recursive
before_script:
  - echo ======= before script start ========
  - export _TOKEN=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
  - export NODESASSBINARY=${CI_PROJECT_DIR}/npm_bindings/node_sass/linux_64/linux-x64-83_binding.node
  - export GENERATE_SOURCEMAP=false
  - node -v
  - npm -v
  - unset CI
  - npm config set sass_binary_path=$NODESASSBINARY
  - echo ======= before script done ========
cache:
  paths:
  - node_modules/
build_project:
  stage: build
  script:
    - echo ======= build started ========
    - npm install
    - npm run-script test:coverage
    - npm run-script dist
    - cd dist
    - npm pack
    - echo ======= build finished ========
  artifacts:
      reports:
        junit:
          - coverage/server/junit.xml
          - coverage/ui/junit.xml
      paths:
        - dist/*.tgz
      expire_in: 24 hrs
  only:
    - master
    - merge_requests
build_release:
  stage: build
  script:
    - echo ======= release started ========
    - npm version $CI_COMMIT_TAG
    - npm install
    - npm run-script test:coverage
    - npm run-script dist
    - cd dist
    - npm publish
    - echo ======= release finished ========
  artifacts:
      reports:
        junit:
          - coverage/server/junit.xml
          - coverage/ui/junit.xml
      paths:
        - dist/*.tgz
      expire_in: 48 hrs
  only:
    - tags