module.exports = {
  globals: {
    path: '/content/admin/root',
  },
  urls: {
    protected: ['content/admin/(?!(login|register|forgotpassword)$).*$'],
  },
  apis: {
    user: '/api/v1/admin/user',
    userInfo: '/api/v1/admin/user/info',
    userRoles: '/api/v1/admin/role',
    searchRole: '/api/v1/admin/role/search',
    roleMapping: '/api/v1/admin/role/mapping',
    getUsers: '/api/v1/admin/users/all',
    searchUsers: '/api/v1/admin/users/search',
    searchEmailTemplates: '/api/v1/admin/emailtemplate/search',
    getPage: '/api/v1/admin/content/page/get',
    getFieldsMeta: '/api/v1/admin/content/page/getfieldsmeta',
    getPageByPath: '/api/v1/admin/content/page/getbypath',
    getContentTree: '/api/v1/admin/content/page/gettree',
    contentPage: '/api/v1/admin/content/page',
    clonePage: '/api/v1/admin/content/page/clone',
  },
  urlMapping: {
    login: '/content/admin/login',
    register: '/content/admin/register',
    adminDashboard: '/content/admin/portal/dashboard',
    createNewEmailTemplate: '/content/admin/portal/emailtemplates/new',
    usersList: '/content/admin/portal/users',
    createNewUser: '/content/admin/portal/users/create',
    editEmailTemplate: '/content/admin/portal/emailtemplates/edit',
    editUser: '/content/admin/portal/users/edit',
    emailTemplatelList: '/content/admin/portal/emailtemplates',
    editPage: '/content/admin/portal/pages/edit',
    editSiteMap: '/content/admin/portal/pages/editmap',
    addNewPage: '/content/admin/portal/pages/create',
    previewDraftPage: '/content/admin/portal/pages/previewdraft',
    '/content/(.*)': {
      type: 'regex',
      target: '/content/$1',
    },
  },
};
